guest_name = ['Tommy', 'Jack', 'Frankline']
print(guest_name)
print("I would like to invite the following people to the dinner:\n\t" + guest_name[0] + "\n\t" + guest_name[1] + "\n\t" + guest_name[2]) 
print(guest_name[2] + " can't attend the party on time\t")
guest_name[2] = 'Sam'
print(guest_name)
guest_name.append('Bingo')
guest_name.append('Alpha')
guest_name.append('Alice')
print(guest_name)
guest_name.insert(0, 'King')
print(guest_name)
guest_name.insert(3, 'Middle')
print(guest_name)
guest_name.append('Last')
print(guest_name)
print("The restraunt can't only accomodate 2 guests.")
guest_name.pop()
print(guest_name)
guest_name.pop()
print(guest_name)
guest_name.pop()
print(guest_name)
guest_name.pop()
print(guest_name)
guest_name.pop()
print(guest_name)
guest_name.pop()
print(guest_name)
guest_name.pop()
print(guest_name)
del guest_name[1]
del guest_name[0]
print(guest_name)

