favorite_destination = ['paris', 'new york', 'los angles', 'tokyo', 'singapore']
print("The original favorite destination list is:\n")
print(favorite_destination)
print(sorted(favorite_destination))
print(favorite_destination)
reversed_destination = sorted(favorite_destination)
reversed_destination.reverse()
print(reversed_destination)
print(favorite_destination)
favorite_destination.reverse()
print(favorite_destination)
favorite_destination.reverse()
print(favorite_destination)
favorite_destination.sort()
print(favorite_destination)
favorite_destination.sort(reverse=True)
print(favorite_destination)
len(favorite_destination)
print("I have " + str(len(favorite_destination)) + " favorite destinations!")
print(favorite_destination[-1])
print(favorite_destination[len(favorite_destination)-2])